### ISSUE TITLE
Segmentation fault with crypto++-8.4.0 (4.3.9)

### ISSUE THREAD

**Issue by michojel** [meganz/MEGAsync#542]
Hi,

on NixOS, when compiled against crypto++-8.4.0, megasync crashes:

```
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 24df8c7d466909deaae5e06fb23530d3
Version code: 4309.0
Module name: megasync
Timestamp: 1613539082694
Operating system: Linux
System version:  nixos 20.09.3152/#1-NixOS SMP Wed Feb 10 08:25:33 UTC 2021
System release:  5.4.97
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x20
Stacktrace:
/nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8(_ZN8CryptoPP16IteratedHashBaseIjNS_18HashTransformationEE14TruncatedFinalEPhm+0x1c0) [0x7f2db18e1990]
/nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8(_ZN8CryptoPP16IteratedHashBaseIjNS_18HashTransformationEE14TruncatedFinalEPhm+0x1c0) [0x7f2db18e1990]
/nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8(_ZN8CryptoPP10RandomPool18IncorporateEntropyEPKhm+0xda) [0x7f2db192ed7a]
/nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8(_ZN8CryptoPP20AutoSeededRandomPool6ReseedEbj+0x43) [0x7f2db1915323]
result/bin/megasync() [0x5d79d1]
result/bin/megasync() [0x6d1207]
result/bin/megasync() [0x6d1b8b]
result/bin/megasync() [0x66b51f]
result/bin/megasync() [0x7b9ac5]
result/bin/megasync() [0x49495f]
/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6(__libc_start_main+0xed) [0x7f2daf675ded]
result/bin/megasync() [0x4966ba]
```

Tried both with 4.3.9.0 and 4.3.5.0.

It works when compiled against crypto++-8.2.0

Related NixOS issues:
- https://github.com/NixOS/nixpkgs/issues/113351
- https://github.com/NixOS/nixpkgs/issues/112572

gdb shows (with incomplete debug symbols):
```
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/g490crrmig6ffbjk5qxd5siavypng6ld-gcc-9.3.0-lib".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/nix/store/i7whvsja1685bdrpxhgynhzryzz9lkx8-megasync-4.3.9.0/bin/.megasync-wrap'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fda4459b990 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::TruncatedFinal(unsigned char*, unsigned long) () from /nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8
[Current thread is 1 (LWP 29658)]
warning: File "/nix/store/sipmc4wnbcws4vahqlf5i06zz7xgnp23-gcc-10.2.0-lib/lib/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/g490crrmig6ffbjk5qxd5siavypng6ld-gcc-9.3.0-lib".
(gdb) bt
#0  0x00007fda4459b990 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::TruncatedFinal(unsigned char*, unsigned long) () from /nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8
#1  0x00007fda445e8d7a in CryptoPP::RandomPool::IncorporateEntropy(unsigned char const*, unsigned long) () from /nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8
#2  0x00007fda445cf323 in CryptoPP::AutoSeededRandomPool::Reseed(bool, unsigned int) () from /nix/store/nf9vk0s2w5w9xqw70jdzizbnq8bipr7c-crypto++-8.4.0/lib/libcryptopp.so.8
#3  0x00000000005d79d1 in ?? ()
#4  0x00000000006d1207 in ?? ()
#5  0x00000000006d1b8b in ?? ()
#6  0x000000000066b51f in ?? ()
#7  0x00000000007b9ac5 in ?? ()
#8  0x000000000049495f in ?? ()
#9  0x00007fda4232fded in __libc_start_main () from /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6
#10 0x00000000004966ba in ?? ()
```

**Comment by michojel** [comment]
Resolved by updating to 4.4.0.0
