### ISSUE TITLE
Segmentation fault on Ubuntu 17.4

### ISSUE THREAD

**Issue by schnittchen** [meganz/MEGAsync#90]
```
(gdb) run
Starting program: /usr/bin/megasync 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9c4e700 (LWP 14000)]
[New Thread 0x7fffe8c0e700 (LWP 14001)]
[New Thread 0x7fffe3fff700 (LWP 14002)]
[Thread 0x7fffe3fff700 (LWP 14002) exited]
[Thread 0x7fffe9c4e700 (LWP 14000) exited]
[New Thread 0x7fffe9c4e700 (LWP 14003)]
[New Thread 0x7fffe3fff700 (LWP 14004)]

Thread 1 "megasync" received signal SIGSEGV, Segmentation fault.
0x00007ffff75bf1fc in CryptoPP::Rijndael::Enc::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const () from /usr/lib/x86_64-linux-gnu/libcrypto++.so.6
(gdb) where
#0  0x00007ffff75bf1fc in CryptoPP::Rijndael::Enc::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const () from /usr/lib/x86_64-linux-gnu/libcrypto++.so.6
#1  0x00007ffff75ba08d in CryptoPP::RandomPool::GenerateIntoBufferedTransformation(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long) ()
   from /usr/lib/x86_64-linux-gnu/libcrypto++.so.6
#2  0x00007ffff74dc9a0 in CryptoPP::RandomNumberGenerator::GenerateBlock(unsigned char*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libcrypto++.so.6
#3  0x00005555556d69a2 in mega::PrnGen::genblock (buf=<optimized out>, len=<optimized out>)
    at mega/src/crypto/cryptopp.cpp:36
#4  0x00005555556d69d7 in mega::PrnGen::genuint32 (max=max@entry=26) at mega/src/crypto/cryptopp.cpp:44
#5  0x000055555569f50a in mega::MegaClient::MegaClient (this=0x555556162750, a=0x5555560d61f0, w=0x55555614fc50, 
    h=0x5555560d9cc0, f=<optimized out>, d=0x55555614ff70, g=0x55555614ff30, 
    k=0x5555558a3a48 <Preferences::CLIENT_KEY> "FhMgXbqb", 
    u=0x5555558a3a30 <Preferences::USER_AGENT> "MEGAsync/3.0.1.0") at mega/src/megaclient.cpp:858
#6  0x00005555556ff030 in mega::MegaApiImpl::init (this=this@entry=0x5555560d61f0, api=api@entry=0x5555560dab20, 
    appKey=appKey@entry=0x5555558a3a48 <Preferences::CLIENT_KEY> "FhMgXbqb", processor=processor@entry=0x0, 
    basePath=basePath@entry=0x5555560d36d8 "/home/thomas/.local/share/data/Mega Limited/MEGAsync/", 
    userAgent=userAgent@entry=0x5555558a3a30 <Preferences::USER_AGENT> "MEGAsync/3.0.1.0", fseventsfd=-1)
    at mega/src/megaapi_impl.cpp:3625
#7  0x000055555570d547 in mega::MegaApiImpl::MegaApiImpl (this=0x5555560d61f0, api=0x5555560dab20, 
    appKey=0x5555558a3a48 <Preferences::CLIENT_KEY> "FhMgXbqb", 
    basePath=0x5555560d36d8 "/home/thomas/.local/share/data/Mega Limited/MEGAsync/", 
    userAgent=0x5555558a3a30 <Preferences::USER_AGENT> "MEGAsync/3.0.1.0") at mega/src/megaapi_impl.cpp:3534
#8  0x00005555556e75d3 in mega::MegaApi::MegaApi (this=0x5555560dab20, 
    appKey=0x5555558a3a48 <Preferences::CLIENT_KEY> "FhMgXbqb", 
    basePath=0x5555560d36d8 "/home/thomas/.local/share/data/Mega Limited/MEGAsync/", 
    userAgent=0x5555558a3a30 <Preferences::USER_AGENT> "MEGAsync/3.0.1.0") at mega/src/megaapi.cpp:1246
#9  0x00005555557b0364 in MegaApplication::initialize (this=0x7fffffffda30) at MegaApplication.cpp:608
#10 0x00005555555c4997 in main (argc=<optimized out>, argv=0x7fffffffde78) at MegaApplication.cpp:315
```

**Comment by polmr** [comment]
@schnittchen, did you download the client for Ubuntu 17.04 from https://mega.nz/sync, or have the one for ubuntu 16.XX running after updating from Ubuntu 16 to Ubuntu 17 ? If you have upgraded your system, you need to either get the latest version from the web or update your megasync repository at /etc/apt/sources.list.d/megasync.list to point to 17.04 and update megasync.

**Comment by schnittchen** [comment]
I upgraded, as you said.

I reverted back to ubuntu 16.10 from a backup, so I'm unable to reproduce right now. I intend to try to upgrade again when things have had time to stabilize.

**Comment by kuzyk** [comment]
I try to install client from web but have same error

  Removing megasync:amd64 because I can't find libcrypto++6:amd64

**Comment by polmr** [comment]
libcrypto++6 is in the official Ubuntu 17.04 repositories:
```
apt-cache search libcrypto++ | grep libcrypto++6
libcrypto++6 - General purpose cryptographic library - shared library
libcrypto++6-dbg - General purpose cryptographic library - debug symbols
```
Ensure you have your repositories configured correctly in your Ubuntu 17.04

**Comment by schnittchen** [comment]
The issue disappeared after installing the latest version.
